### ISSUE TITLE
Babel and postcss should share browserlist config

### ISSUE THREAD

**Issue by ryuran** [tr1s/tris-webpack-boilerplate#12]
Hello @tr1s 
I think `postcss.config.js` should be in root directory.
And `autoprefixer` and `@babel/preset-env` should refer to `.browserlistrc`

**Comment by tr1s** [comment]
@ryuran the `postcss.config.js` works at the root of the `src` folder and I think it makes sense being there. Do you know if it works on the root of the project too?

Can you please provide an example of `autoprefixer` / `babel` referring to a `.browserlistrc` file? Feel free to submit a PR and send some reading material regarding this matter.

Thank you!

**Comment by tr1s** [comment]
@larenelg @michael-wolfenden @ryuran looked into it, added the browserslist and got rid of the .babelrc, so now babel and autoprefixer are running through it. Tested with different percentages just to make sure.

**Comment by ryuran** [comment]
@tr1s `@babel/preset-env` recommand to use `.browserlistrc` file
https://babeljs.io/docs/en/babel-preset-env#browserslist-integration
> For browser- or Electron-based projects, we recommend using a `.browserslistrc` file to specify targets. You may already have this configuration file as it is used by many tools in the ecosystem, like `autoprefixer`, `stylelint`, `eslint-plugin-compat` and many others. 
>
> By default `@babel/preset-env` will use [browserslist config sources](https://github.com/browserslist/browserslist#queries)

Same for autoprefixer https://github.com/postcss/autoprefixer#browsers
>The best way to provide browsers is a .browserslistrc file in your project root, or by adding a browserslist key to your package.json.
>
>We recommend the use of these options over passing options to Autoprefixer so that the config can be shared with other tools such as babel-preset-env and Stylelint.

I can provide a PR later (it's 2am here)

> the postcss.config.js works at the root of the src folder and I think it makes sense being there.

Maybe. Usualy I put every config file at root of project. I'm not sure about which is the best way.
```
postcss.config.js
babel.config.js
.eslintrc.js
.editorconfig
webpack.config.js
```

**Comment by tr1s** [comment]
@ryuran I got my info right from the browserslist github... idk why autoprefixer/babel are saying different. 🤔

<img width="955" alt="cleanshot 2019-01-29 at 22 13 48 2x" src="https://user-images.githubusercontent.com/19172250/51955811-3a251c80-2413-11e9-83f3-e1f600b7660b.png">

I guess the `postcss.config.js` being with the rest of the configs in root would make sense... not that big of a deal in general. Trying to think of what's more intuitive.

Can you test in the AM if it works?

**Comment by ryuran** [comment]
By habit, I separate every config files and put in at root directory.

It’s not your choice:
- browserlist config is in package.json
- postcss config is in a sub directory (the one with css, it make sense)
- babel config is inline in webpack config file

For me it’s not consistant enough. I can’t understand a logic.

Why babel config is inline in webpack and not postcss config ?

If I need to add eslint config, It should be in `.eslinrc.js` or `.eslinrc.json` in root directory, or rules should be in `package.json` ?
