### ISSUE TITLE
json files

### ISSUE THREAD

**Issue by arbel** [tr1s/tris-webpack-boilerplate#15]
Hello,

I'm using Lottie and need to refrence a json file in my script.
I tried placing it a few places in my src folder but when I preview the file I get a message that the json file cannot be found. is there something else I need to do in the config so I can use json assets?

**Comment by arbel** [comment]
this is my code
'var animation = bodymovin.loadAnimation({
	  container: document.getElementById('ui-anim'),
	  renderer: 'svg',
	  loop: true,
	  autoplay: true,
	  path: 'images/ui.json'
	});'

and I have a file ui.json in my src/images folder

**Comment by tr1s** [comment]
Did you figure it out? Maybe try [json-loader](https://webpack.js.org/loaders/json-loader/).
