### ISSUE TITLE
js-yaml vulnerabilities

### ISSUE THREAD

**Issue by MelanieL** [tr1s/tris-webpack-boilerplate#23]
Thanks again for the awesome boilerplate. I've learned so much using it!

I noticed today I'm having some dependency issues with js-yaml in the postcss-loader. I tried to fix it by updating on my own, but I'm not sure I can. The code injection vulnerability sounds particularly unfriendly.

Not sure if this is a real issue or not, but definitely curious to learn more about a fix.

**Comment by tr1s** [comment]
Are you having issues besides it just being a vulnerability?

You can't really update deeper dependencies (js-yaml) of the top level dependencies (post-css). Generally just reach out to post-css in an issue and let them know what's going on. They'll either already know and are working on a fix, or working on updating their dependencies without breaking anything. Or may even provide a temp fix.

Npm just says to [update js-yaml to 3.13.1](https://www.npmjs.com/advisories/813), and we're on 3.13.0. But there might be a reason why they haven't yet.

If you look into it more, let me know what you figure out :)

**Comment by tr1s** [comment]
@MelanieL 

So, it finally got sorted out! Sometimes you just have to wait.

This is the email I got, and refer to [this pull request](https://github.com/tr1s/tris-webpack-boilerplate/pull/24) that automatically fixed it for me. 

<img width="1124" alt="Screenshot 2019-06-05 14 36 40" src="https://user-images.githubusercontent.com/19172250/59032462-5ce99680-8834-11e9-8666-e6db720922f8.png">

They got bots that do the dirty work now!

**Comment by MelanieL** [comment]
Sweet, thanks!!!
