### ISSUE TITLE
img directory start with / (slash) in production mode

### ISSUE THREAD

**Issue by bnhr** [tr1s/tris-webpack-boilerplate#26]
When it's come to production mode, all images are not displayed, it starts with "/images" not "images", how to change it?

**Comment by shyamlohar** [comment]
@tr1s it is not supposed to cause any issue. I have personally tested it and even have live project which uses that config.
@bnhr I would like to see how you are referencing images in your HTML. and what your project structure looks like. it's not supposed to cause issues.

**Comment by shyamlohar** [comment]
meanwhile if you would like to change that path anyway 

in webpack.common.js file replace publicPath from `'/images/'` to `'images'` in following lines

`{
        test: /\.(jpe?g|png|gif|svg)$/,
        use: [{
          loader: 'file-loader',
          options: {
            name: '[name].[ext]',
            outputPath: 'images/',
            publicPath: '/images/'
          }
        }]
      },`

**Comment by bnhr** [comment]
@shyamlohar I'm trying use 2 methods
first one is :
`<img loading="lazy" src="../src/images/svg/follow.svg">`
and second is :
`<img loading="lazy" src="images/news.jpg">`

after I change the webpack.common.js file, it's work just fine, all of them...
Thank you

**Comment by tr1s** [comment]
@bnhr I'm also curious about how your project was set up. 

I did a fresh clone and deployed the site when an extra image and everything rendered out fine. I would like to know what specifically caused the current config not to work for you!

Let me know, cheers
