### ISSUE TITLE
[Question]: NekR/offline-plugin vs GoogleChrome/workbox

### ISSUE THREAD

**Issue by pruett** [tr1s/tris-webpack-boilerplate#3]
Curious if you have used `workbox` (https://github.com/googlechrome/workbox) to handle offline/ServiceWorker capability? I don't have a personal opinion, but was curious if you've evaluated it and/or used it in the past. Thanks!

**Comment by tr1s** [comment]
@pruett Tbh I have never heard of it nor used it, sorry. If you do decide to try it out and implement it, let me know how it goes!

**Comment by pruett** [comment]
will do. great boilerplate + explanation!
