### ISSUE TITLE
Can't open localhost on mobile through IP address

### ISSUE THREAD

**Issue by szymonhernik** [tr1s/tris-webpack-boilerplate#30]
Hi, I'm trying to open my running server on my mobile. On mobile, in a browser, I'm writing in a following way: 192.168.178.11:8080. The website on mobile doesn't open at all—the server is running all the time. Haven't had problems with this task before when using other webpacks. Thanks!

**Comment by shyamlohar** [comment]
For now you can do webpack-dev-server --open --config webpack.dev.js --allowedhosts *insert your host here*
