### ISSUE TITLE
Preload fonts

### ISSUE THREAD

**Issue by Munter** [tr1s/tris-webpack-boilerplate#7]
A big detractor for rendering performance is the flash of invisible text in the period between first paint and webfonts being loaded.

This period can be reduced with `<link rel="preload">` for the require web fonts, or other more complex optimizations can be achieved with fontfaceobserver, automated font subsetting, `font-display` etc.

To keep performance high when user start building new content from this scaffold, it would be very helpful if the template came with an already existing optimization strategy

**Comment by tr1s** [comment]
Will look into [preload-webpack-plugin](https://www.npmjs.com/package/preload-webpack-plugin) this week.

**Comment by tr1s** [comment]
@Munter No luck.

I've tried and made an issue over at [preload-webpack-plugin issues](https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/89) so we'll see what they say. 

If anyone reading this would like to try and see what I'm doing wrong, that'd be great!

**Comment by Munter** [comment]
The case of preloading deep dependency graph elements is indeed not one that fits super well into the webpack plugin ecosystem. At least not while html is still treated as a templating string.

I built a tool to solve this problem outside of webpack. It's called [subfont](https://www.npmjs.com/package/subfont). But since it doesn't fit right into webpack, and instead has to be run as a post-process after webpack, I'm unsure of whether the tool fits into the flow you are trying to scaffold

**Comment by tr1s** [comment]
Alright, thanks. I'll keep this open until I get a response on the other end.

**Comment by tr1s** [comment]
Done and done!
